config/routes.rb
Rails.application.routes.draw do

  #items
  get 'items/', to: "items#index", as: "items"
  post 'items/', to: "items#create"
  get 'items/new', to: "items#new", as: "new_item"
  get 'items/toys', to: "items#toys", as: "toys"
  get 'items/books', to: "items#books", as: "books"
  get 'items/clothes', to: "items#clothes", as: "clothes"
  get 'items/accessories', to: "items#accessories", as: "accessories"
  get 'items/:id/edit', to: "items#edit", as: "edit_item"
  patch "items/:id/", to: "items#update"
  put "items/:id/", to: "items#update"
  get 'items/:id', to: "items#show", as: "item"
  delete "items/:id", to: "items#destroy"



  root to: "homepage#index"
  devise_for :user

  #seller
  get 'seller/:seller_id/sold', to: "seller#sold", as: "sold_items"
  get 'seller/:seller_id', to: "seller#index", as: "seller"

  #buyer
  get 'buyer/:buyer_id', to: "buyer#purchased", as: "purchased_items"

  #purchases
  get 'purchases/new', to: "purchases#new", as: "new_purchase"
  get 'purchases/complete/:id', to: "purchases#complete", as: "completed_purchase"
  get 'purchases/receipt/:id', to: "purchases#receipt", as: "purchase_receipt"

end

app/controllers/buyer_controller.rb
class BuyerController < ApplicationController

  # For the view to see what a user has purchased
  def purchased
    @items = Purchase.items_buyer_has_purchased(current_user)

    # this is to make the user menu work easily
    @user = current_user
  end
end

app/helpers/buyer_helper.rb
module BuyerHelper
end

app/views/buyer/purchased.html.erb
 <%= render "shared/usermenu"%>

<%# I had to use @items.length > 0 because a user (with no items) has a blank active record. If I just put `if @items`, ruby thinks this is true %>
<% if @items.length > 0%>
<h2 class="title">Items <%= current_user.username %> has purchased </h2>


<div class ="items">
<% @items.each do |i| %>
    <div class="item-div">
        <p>
            <% if i.item.photo.attachment %>
                <%= link_to image_tag(i.item.photo, class: "items-image"), purchase_receipt_path(i.item.id)%>
            <%end%>
        </p>
        <p><%= link_to i.item.title, purchase_receipt_path(i.item.id) %></p>
        <p><%= number_to_currency(i.item.price)%></p>
        <p><strong>Purchased:</strong> <%= i.created_at.to_date%></p>
        <p><strong>Seller:</strong> <%= i.item.seller.username %></p>
        <p><strong>Seller's Email:</strong> <%= i.item.seller.email %></p>
    </div>
<% end%>
</div>

<%else%>
    <h3 class="title has-text-centered"><%=current_user.username%> currently has bought no items</h3>
<%end%>