config/routes.rb
Rails.application.routes.draw do

  #items
  get 'items/', to: "items#index", as: "items"
  post 'items/', to: "items#create"
  get 'items/new', to: "items#new", as: "new_item"
  get 'items/toys', to: "items#toys", as: "toys"
  get 'items/books', to: "items#books", as: "books"
  get 'items/clothes', to: "items#clothes", as: "clothes"
  get 'items/accessories', to: "items#accessories", as: "accessories"
  get 'items/:id/edit', to: "items#edit", as: "edit_item"
  patch "items/:id/", to: "items#update"
  put "items/:id/", to: "items#update"
  get 'items/:id', to: "items#show", as: "item"
  delete "items/:id", to: "items#destroy"



  root to: "homepage#index"
  devise_for :user

  #seller
  get 'seller/:seller_id/sold', to: "seller#sold", as: "sold_items"
  get 'seller/:seller_id', to: "seller#index", as: "seller"

  #buyer
  get 'buyer/:buyer_id', to: "buyer#purchased", as: "purchased_items"

  #purchases
  get 'purchases/new', to: "purchases#new", as: "new_purchase"
  get 'purchases/complete/:id', to: "purchases#complete", as: "completed_purchase"
  get 'purchases/receipt/:id', to: "purchases#receipt", as: "purchase_receipt"

end

app/views/shared/_displayitems.html.erb
<div class ="items">
<% if @items.length > 0 %>
    <% @items.each do |item| %>
            <div class="item-div">
                <% if item.photo.attachment %>
                    <p><%= link_to image_tag(item.photo, class: "items-image"), item_path(item)%></p>
                <%end%>
                <p><%= link_to item.title, item_path(item) %></p>
                <p><%= number_to_currency(item.price)%></p>
                <p><%= link_to 'Buy Now', new_purchase_path(id: item.id), class: "button is-primary", data: { turbolinks: false } %></p>
            </div>
    <%end%>
<%else%>
<p>Currently no items!</p>
<%end%>
</div>

app/views/shared/_header.html.erb
<div class="level-item">
    <p class="subtitle is-5"><%= link_to "Kid's World", root_path %></p>

</div>
<div class="level-item">
    <%= link_to "Toys", toys_path %>
</div>

<div class="level-item">
    <%= link_to "Books", books_path %>
</div>

<div class="level-item">
    <%= link_to "Clothes", clothes_path %>
</div>

<div class="level-item">
    <%= link_to "Accessories", accessories_path %>
</div>
 <% if user_signed_in? %>
<div class="level-item">
    <%= link_to 'Sell a New Item', new_item_path, class: "button is-success is-outlined" %>
</div>
 <% end %>

app/views/shared/_signin.html.erb
  <% if user_signed_in? %>
    <div id="logout" class="level-item"><%= link_to 'Logout', destroy_user_session_path, method: "delete",class:"top-nav-link"%></div>
    <div id="username" class="level-item"><%= link_to current_user.name, seller_path(current_user) %></div>
  <% else %>
   <div class="level-item"><%= link_to 'Login', new_user_session_path, class:"top-nav-link"%></div>
   <div class="level-item"><%= link_to 'Sign Up', new_user_registration_path, class:"top-nav-link"%></div>
 <% end %>

app/views/shared/_usermenu.html.erb
<% if @user == current_user %>
    <%= link_to 'Your items for sale', seller_path(current_user), class: "button is-info" %>
    <%= link_to 'Your sold items', sold_items_path(@user.id), class: "button is-info" %>
    <%= link_to 'Your purchased items', purchased_items_path(@user.id), class: "button is-info" %>
    <p>&nbsp;</p>
<%end%>